# Generated by Django 5.0.2 on 2024-04-22 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='annualRegistration',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birthDate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birthDateChecked',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='completedProfile',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='creationDate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='faceIdentityChecked',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='identityPhotoID',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lastUpdateDate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='levelNumber',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profilePhotoID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='annualRegistration',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthDate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthDateChecked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='completedProfile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='creationDate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='faceIdentityChecked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='identityPhotoID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastUpdateDate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='levelNumber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profilePhotoID',
        ),
    ]
