# Generated by Django 5.0.2 on 2024-04-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_annualregistration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
